environment:
    matrix:
        - PYTHON: "C:\\Python27"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "pip install -r requirements.txt"
    - "pip install pyinstaller"

build_script:
    - "pyinstaller lakeception.spec"

artifacts:
    - path: dist\lakeception.exe
      name: lakeception
      type: zip

deploy:
    provider: GitHub
    description: "Build {build}"
    artifact: lakeception
    draft: false
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: false
    auth_token:
        secure: gC9PCTALEryiNW7gtwWeabnCH8P/NReiNlL6zU7jkzHZDWiLa/SEd/HECwYOxXof
